base_url = "https://cervthecoder.github.io/krajinazaskolou"
compile_sass = true
title = "Krajina za školou"
description = ""
generate_feed = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[extra]
author = "Matěj Červenka"
after_dark_title = "Krajina za školou"
